SELECT  S.AUTHOR_ID, A2.AUTHOR_NAME, S.CATEGORY, S.TOTAL_SALES
FROM    AUTHOR A2
INNER   JOIN (SELECT  A.AUTHOR_ID, B.CATEGORY, SUM(S.SALES * B.PRICE) TOTAL_SALES
        FROM    BOOK_SALES S, AUTHOR A, BOOK B
        WHERE   S.BOOK_ID = B.BOOK_ID
                AND A.AUTHOR_ID = B.AUTHOR_ID
                AND TO_CHAR(S.SALES_DATE, 'YYYY-MM') = '2022-01'
        GROUP   BY A.AUTHOR_ID, B.CATEGORY) S
ON      A2.AUTHOR_ID = S.AUTHOR_ID
ORDER   BY S.AUTHOR_ID ASC, S.CATEGORY DESC
