SELECT  A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, A.TOTAL_SALES
FROM    (SELECT  B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE * S.TOTAL_SALES) AS TOTAL_SALES
        FROM    (SELECT  BOOK_ID, SUM(SALES) AS TOTAL_SALES
                FROM    BOOK_SALES
                WHERE   TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
                GROUP   BY BOOK_ID) S
        INNER   JOIN BOOK B
        ON      B.BOOK_ID = S.BOOK_ID
        GROUP   BY B.AUTHOR_ID, B.CATEGORY
        ORDER   BY B.AUTHOR_ID ASC, B.CATEGORY DESC) A
INNER   JOIN AUTHOR B
ON      A.AUTHOR_ID = B.AUTHOR_ID