SELECT ROUND(AVG(A.LENGTH), 2) AS AVERAGE_LENGTH
FROM ((SELECT  10 AS LENGTH
        FROM    FISH_INFO
        WHERE   LENGTH IS NULL)
        UNION ALL
        (SELECT  LENGTH AS LENGTH
        FROM    FISH_INFO
        WHERE   LENGTH IS NOT NULL)) A