SELECT  C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100 AS FEE
FROM    CAR_RENTAL_COMPANY_CAR C
INNER   JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON      C.CAR_TYPE = P.CAR_TYPE
WHERE   C.CAR_TYPE IN ('세단', 'SUV')
AND     P.DURATION_TYPE = '30일 이상'
AND     C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100 BETWEEN 500000 AND 2000000
AND     C.CAR_ID NOT IN (SELECT  CAR_ID
                        FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE   TO_CHAR(END_DATE, 'YYYY-MM') = '2022-11'
                        OR      TO_CHAR(START_DATE, 'YYYY-MM') = '2022-11'
                        OR      TO_CHAR(START_DATE, 'YYYY-MM') < '2022-11' AND TO_CHAR(END_DATE, 'YYYY-MM') > '2022-11')
ORDER   BY FEE DESC, P.CAR_TYPE ASC, C.CAR_ID DESC