SELECT  M.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM (SELECT  FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM    REST_INFO
    GROUP   BY FOOD_TYPE) M, REST_INFO R
WHERE   M.FAVORITES = R.FAVORITES
    AND M.FOOD_TYPE = R.FOOD_TYPE
ORDER   BY M.FOOD_TYPE DESC;