SELECT  R.REST_ID, R.REST_NAME, R.FOOD_TYPE, R.FAVORITES, R.ADDRESS, A.SCORE
FROM    REST_INFO R
INNER   JOIN (SELECT    REST_ID, ROUND(AVG(REVIEW_SCORE), 2) SCORE
              FROM      REST_REVIEW
              GROUP     BY REST_ID) A
ON      R.REST_ID = A.REST_ID
WHERE   R.ADDRESS LIKE '서울%'
ORDER   BY 6 DESC, 4 DESC;


