SELECT  I.REST_ID AS REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, R.SCORE
FROM    (SELECT  REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
        FROM    REST_REVIEW
        GROUP   BY REST_ID) R, REST_INFO I
WHERE   R.REST_ID = I.REST_ID
        AND I.ADDRESS LIKE '서울%'
ORDER   BY R.SCORE DESC, I.FAVORITES DESC;