SELECT  EXTRACT(YEAR FROM O.SALES_DATE) AS YEAR
        , EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH
        , U.GENDER
        , COUNT(DISTINCT O.USER_ID) AS USERS
FROM    USER_INFO U, ONLINE_SALE O
WHERE   U.USER_ID = O.USER_ID
        AND U.GENDER IS NOT NULL
GROUP   BY EXTRACT(YEAR FROM O.SALES_DATE), EXTRACT(MONTH FROM O.SALES_DATE), GENDER
ORDER   BY EXTRACT(YEAR FROM O.SALES_DATE), EXTRACT(MONTH FROM O.SALES_DATE), GENDER