SELECT  TO_NUMBER(TO_CHAR(S.SALES_DATE, 'YYYY')) YEAR
        , TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) MONTH
        , U.GENDER
        , COUNT(DISTINCT U.USER_ID) AS USERS
FROM    ONLINE_SALE S
INNER   JOIN USER_INFO U
ON      U.USER_ID = S.USER_ID
WHERE   U.GENDER IS NOT NULL
GROUP   BY TO_NUMBER(TO_CHAR(S.SALES_DATE, 'YYYY'))
        , TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM'))
        , U.GENDER
ORDER   BY 1 ASC, 2 ASC, 3 ASC