SELECT  S.CAR_ID, NVL2(MAX(S.AVAILABILITY), MAX(S.AVAILABILITY), '대여 가능') AVAILABILITY
FROM    (SELECT  CAR_ID
                ,CASE WHEN TO_DATE('2022-10-16', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE THEN '대여중' END AVAILABILITY
        FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY
        ORDER   BY CAR_ID DESC) S, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE   S.CAR_ID = H.CAR_ID
GROUP   BY S.CAR_ID
ORDER   BY S.CAR_ID DESC;
