SELECT  DISTINCT CAR_ID
        , CASE WHEN CAR_ID IN ( SELECT  CAR_ID
                    FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE   TO_CHAR(START_DATE, 'YYYY-MM-DD') <= '2022-10-16'
                            AND TO_CHAR(END_DATE, 'YYYY-MM-DD') >= '2022-10-16')
                THEN '대여중'
                ELSE '대여 가능' END AVAILABILITY
FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER   BY CAR_ID DESC;
