SELECT  P.PRODUCT_ID, P.PRODUCT_NAME, S.TOTAL_AMOUNT * P.PRICE AS TOTAL_SALES
FROM (
        SELECT  PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
        FROM    FOOD_ORDER
        WHERE   TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
        GROUP   BY PRODUCT_ID
) S, FOOD_PRODUCT P
WHERE   P.PRODUCT_ID = S.PRODUCT_ID
ORDER   BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;