SELECT  H.HISTORY_ID
        , CASE WHEN END_DATE-START_DATE+1 BETWEEN 7 AND 29
        THEN (H.END_DATE-H.START_DATE+1) * C.DAILY_FEE * (100-(SELECT DISCOUNT_RATE
              FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
              WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상'))/100 
        WHEN END_DATE-START_DATE+1 BETWEEN 30 AND 89
        THEN (H.END_DATE-H.START_DATE+1) * C.DAILY_FEE * (100-(SELECT DISCOUNT_RATE
              FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
              WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상'))/100
        WHEN END_DATE-START_DATE+1 >= 90
        THEN (H.END_DATE-H.START_DATE+1) * C.DAILY_FEE * (100-(SELECT DISCOUNT_RATE
              FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
              WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상'))/100
        ELSE (H.END_DATE-H.START_DATE+1) * C.DAILY_FEE
        END AS FEE
FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
INNER   JOIN CAR_RENTAL_COMPANY_CAR C
ON      C.CAR_ID = H.CAR_ID
WHERE   C.CAR_TYPE = '트럭'
ORDER   BY FEE DESC, H.HISTORY_ID DESC;