SELECT  A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM    APPOINTMENT A
INNER JOIN  PATIENT P
ON      A.PT_NO = P.PT_NO
INNER JOIN  DOCTOR  D
ON      D.DR_ID = A.MDDR_ID
WHERE   A.APNT_CNCL_YN != 'Y'
        AND TO_CHAR(A.APNT_YMD, 'YYYY-MM-DD') ='2022-04-13'
        AND A.MCDP_CD = 'CS'
ORDER   BY A.APNT_YMD;
