SELECT  HOUR, MAX(COUNT) COUNT
FROM    (SELECT  TO_NUMBER(TO_CHAR(DATETIME, 'HH24'), '09') HOUR, COUNT(*) COUNT
        FROM    ANIMAL_OUTS 
        GROUP   BY TO_CHAR(DATETIME, 'HH24')
        UNION
        SELECT  LEVEL - 1 HOUR, 0 COUNT
        FROM    DUAL
        CONNECT BY LEVEL <= 24)
GROUP   BY HOUR
ORDER   BY HOUR