SELECT  HOUR, MAX(COUNT) COUNT
FROM ((SELECT  TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR, COUNT(ANIMAL_ID) COUNT
        FROM    ANIMAL_OUTS
        GROUP   BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24')))
        UNION
        (SELECT  LEVEL-1, 0 COUNT
        FROM    DUAL
        CONNECT BY LEVEL <= 24))
GROUP   BY HOUR
ORDER   BY 1 ASC