SELECT  U.USER_ID, U.NICKNAME, S.TOTAL_SALES
FROM    USED_GOODS_USER U
INNER JOIN (SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
        FROM    USED_GOODS_BOARD B
        WHERE   STATUS='DONE'
        GROUP   BY WRITER_ID
        HAVING  SUM(PRICE) >= 700000) S
ON      S.WRITER_ID = U.USER_ID
ORDER   BY S.TOTAL_SALES ASC;