SELECT  U.USER_ID, U.NICKNAME, B.TOTAL_SALES
FROM    (
    SELECT  WRITER_ID, SUM(PRICE) TOTAL_SALES
    FROM    USED_GOODS_BOARD
    WHERE   STATUS = 'DONE'
    GROUP   BY WRITER_ID
    HAVING  SUM(PRICE) >= 700000
) B, USED_GOODS_USER U
WHERE   B.WRITER_ID = U.USER_ID
ORDER   BY B.TOTAL_SALES;