SELECT  G.USER_ID, G.NICKNAME, B.TOTAL_SALES
FROM    USED_GOODS_USER G
INNER   JOIN    (SELECT  WRITER_ID, SUM(PRICE) AS TOTAL_SALES
                FROM    USED_GOODS_BOARD
                WHERE   STATUS = 'DONE'
                GROUP   BY WRITER_ID
                HAVING  SUM(PRICE) >= 700000) B
ON      G.USER_ID = B.WRITER_ID
ORDER   BY B.TOTAL_SALES ASC;