SELECT  TO_NUMBER(TO_CHAR(DATETIME, 'HH24'), '09') HOUR, COUNT(ANIMAL_ID) COUNT
FROM    ANIMAL_OUTS
WHERE   TO_CHAR(DATETIME, 'HH24') BETWEEN 9 AND 19
GROUP   BY TO_CHAR(DATETIME, 'HH24')
ORDER   BY TO_CHAR(DATETIME, 'HH24');