SELECT  M.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM    REST_REVIEW R, MEMBER_PROFILE M
WHERE   M.MEMBER_ID = (SELECT  MEMBER_ID
                    FROM    REST_REVIEW
                    GROUP   BY MEMBER_ID
                    ORDER   BY COUNT(REVIEW_ID) DESC
                    FETCH NEXT 1 ROWS ONLY)
        AND R.MEMBER_ID = M.MEMBER_ID
ORDER   BY TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') ASC, R.REVIEW_TEXT ASC;