SELECT  P.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM    REST_REVIEW R
INNER   JOIN MEMBER_PROFILE P
ON      P.MEMBER_ID = R.MEMBER_ID
WHERE   R.MEMBER_ID = (SELECT  MEMBER_ID
                    FROM    REST_REVIEW
                    GROUP   BY MEMBER_ID
                    ORDER   BY COUNT(MEMBER_ID) DESC
                    FETCH   FIRST 1 ROWS ONLY)
ORDER   BY 3 ASC, 2 ASC;
                    