SELECT  TO_NUMBER(TO_CHAR(START_DATE, 'MM'), '09') AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE   CAR_ID IN (SELECT CAR_ID
                FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE   TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
                GROUP   BY CAR_ID
                HAVING  COUNT(HISTORY_ID) >= 5)
        AND TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
GROUP   BY TO_CHAR(START_DATE, 'MM'), CAR_ID
HAVING  COUNT(HISTORY_ID) != 0
ORDER   BY TO_CHAR(START_DATE, 'MM') ASC, CAR_ID DESC;
