SELECT  F.CATEGORY, S.MAX_PRICE, F.PRODUCT_NAME
FROM (SELECT  MAX(PRICE) AS MAX_PRICE, CATEGORY
        FROM    FOOD_PRODUCT
        WHERE   CATEGORY IN ('과자', '국', '김치', '식용유')
        GROUP   BY CATEGORY) S, FOOD_PRODUCT F
WHERE   S.MAX_PRICE = F.PRICE
        AND S.CATEGORY = F.CATEGORY
ORDER   BY MAX_PRICE DESC;